# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 582c3090bd299407d58d5a6f022d0f14dc93c60410211c9a2272520bc53db9df4b4149e352daa66fe56189576f5bbfffebdc6454163ffa56393c22ffdc96031c

test:
  secret_key_base: 53c950982e4a97f8d5b9c69b6518450f9e0456eb32793244049dbf396f549d05cd605d7cb85aff85c8ca76c18b49567e29939faff4a79343fbb1eb91f1b8c02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
